[build]
  command = "./deploy-netlify.sh"
  publish = "."

# Environment variables are set in Netlify dashboard under Site settings > Environment variables
# DO NOT declare them here with empty values as it overrides the dashboard settings

[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy for Firebase
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.gstatic.com; connect-src 'self' https://*.firebaseio.com wss://*.firebaseio.com; font-src 'self' https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;"

# Handle client-side routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200