[build]
  command = "./deploy-netlify.sh"
  publish = "."

[build.environment]
  # Set these in Netlify dashboard under Site settings > Environment variables
  FIREBASE_API_KEY = ""
  FIREBASE_AUTH_DOMAIN = ""
  FIREBASE_DATABASE_URL = ""
  FIREBASE_PROJECT_ID = ""
  FIREBASE_STORAGE_BUCKET = ""
  FIREBASE_MESSAGING_SENDER_ID = ""
  FIREBASE_APP_ID = ""

[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy for Firebase
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.gstatic.com; connect-src 'self' https://*.firebaseio.com wss://*.firebaseio.com; font-src 'self' https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;"

# Handle client-side routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200